title: Wasim Tamboli # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.E. in Computer Science, Pune University
  <br><br>
  Python Developer, Geospoc
  <br><br>
  <a href="https://www.linkedin.com/in/wt-wasi/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="./pdf/Resume_Wasim.pdf">View My CV</a> 
  <br><br>
  <p>I'm currently looking for python developer opportunities or freelance projects.</p> 
  <br><br>
  <p>If you would like to discuss a project or employment opportunities, please do not hesitate to get in touch.</p> 

  
theme: jekyll-theme-minimal
google_analytics: G-FKHFDRB4SX # your Google Analytics tracking ID here
