title: Abhijeet Jagtap # your name (or website title) here
# the little icon that appears in the browser window's tab
favicon: /favicon.ico
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  B.Sc. in Chemistry, Pune University
  <br><br>
  Deputy Manager - Data Visualization, Vodafone
  <br><br>
  <a href="https://www.linkedin.com/in/abhijeetjagatp/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="Resume_Abhijeet.docx">View My CV</a> 
  <br><br>
  <a href="https://public.tableau.com/profile/abhijeet.jagtap/">View My Tableau Public Profile</a> 
  
  

theme: jekyll-theme-minimal
google_analytics: G-FKHFDRB4SX # your Google Analytics tracking ID here
